# Generated by Django 5.1 on 2025-07-08 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOBBY', 'Лобби'), ('DAY', 'День'), ('NIGHT', 'Ночь'), ('VOTING', 'Голосование'), ('FINISHED', 'Завершена')], default='LOBBY', max_length=10, verbose_name='Стаутус игры')),
                ('players_count', models.IntegerField(default=0, verbose_name='Общее количество игроков')),
                ('mafia_count', models.IntegerField(default=0, verbose_name='Общее количество мафии')),
                ('doctor_count', models.IntegerField(default=0, verbose_name='Общее количество докторов')),
                ('commissioner_count', models.IntegerField(default=0, verbose_name='Общее количество шерифов')),
                ('current_round', models.IntegerField(default=0, verbose_name='Текущий номер хода(0-Лобби,1-День,2-Ночь...)')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания игры')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время старта игры')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения игры')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('role', models.CharField(choices=[('CIVILIAN', 'Мирный житель'), ('MAFIA', 'Мафия'), ('DOCTOR', 'Доктор'), ('COMMISSIONER', 'Комиссар')], max_length=15, verbose_name='Роль')),
                ('is_alive', models.BooleanField(default=True, verbose_name='Жив ли игрок')),
                ('is_host', models.BooleanField(default=False, verbose_name='Является ли игрок ведущим')),
                ('order_in_game', models.IntegerField(default=0, verbose_name='Порядок нумерации игрока в игре')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game_api.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mafia_player_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='Номер хода')),
                ('phase', models.CharField(choices=[('NIGHT', 'Ночь'), ('DAY', 'День'), ('VOTING', 'Голосование')], max_length=10, verbose_name='Фаза(День,ночь,голосование)')),
                ('events', models.TextField(blank=True, verbose_name='Описание событий этого раунда')),
                ('commissioner_check_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_round', to='game_api.player')),
                ('doctor_heal_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healed_in_round', to='game_api.player')),
                ('executed_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_in_round', to='game_api.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game_api.game')),
                ('mafia_kill_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='killed_in_round', to='game_api.player')),
            ],
            options={
                'verbose_name': 'Раунд',
                'verbose_name_plural': 'Раунды',
            },
        ),
        migrations.CreateModel(
            name='PlayerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('VOTE', 'Голосование'), ('MAFIA_KILL', 'Убийство мафии'), ('DOCTOR_HEAL', 'Лечение доктора'), ('COMMISSIONER_CHECK', 'Проверка комиссара')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_actions', to='game_api.player')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_actions', to='game_api.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game_api.round')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
